name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: src/environment.yml
          activate-environment: density_field_properties
          python-version: "3.14"
          cache-environment: true

      - name: Run pre-commit
        run: pre-commit run --all-files --config src/.pre-commit-config.yaml

      - name: Run tests
        working-directory: src
        env:
          PYTHONPATH: .
        run: pytest tests/ -m "not integration"
